import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { getLondonWeather } from "@/lib/weather.js";
const inter = Inter({ subsets: ["latin"] });

export async function getServerSideProps() {
  const weatherData = await getLondonWeather();
  return {
    props: {
      weatherData,
    },
  };
}
export default function Home(props) {
  console.log(getLondonWeather());
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>
          The Current Weather in london is {props.weatherData.main.temp} °C
        </h1>
        <h2>This is defintiely Correct Weather lol</h2>
      </main>
    </>
  );
}
